// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package net.iessonferrer.jgonzalez.billar;

import net.iessonferrer.jgonzalez.billar.enumTipo;

/************************************************************/
/**
 * 
 */
public class Bola {
	/**
	 * 
	 */
	private String color;
	/**
	 * 
	 */
	private int numero;
	/**
	 * 
	 */
	private int posicion_x;
	/**
	 * 
	 */
	private int posicion_y;
	/**
	 * 
	 */
	private int radio;
	/**
	 * 
	 */
	private boolean estado;
	/**
	 * 
	 */
	private enumTipo tipo;

	/**
	 * 
	 */
	public void dibujar() {
	}

	/**
	 * 
	 */
	public void mover() {
	}

	/**
	 * 
	 */
	public void detectarColision() {
	}

	/**
	 * 
	 */
	public void eliminarBola() {
	}

	/**
	 * 
	 */
	public void detectarTronera() {
	}
};
