// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package net.iessonferrer.jgonzalez.billar;

/************************************************************/
/**
 * 
 */
public enum enumTipo {
	/**
	 * 
	 */
	BLANCA,
	/**
	 * 
	 */
	NEGRA,
	/**
	 * 
	 */
	LISA,
	/**
	 * 
	 */
	RAYADA;
};
