// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package net.iessonferrer.jgonzalez.billar;

import net.iessonferrer.jgonzalez.billar.Taco;

/************************************************************/
/**
 * 
 */
public class Jugador {
	/**
	 * 
	 */
	public Taco taco;
};
