// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package net.iessonferrer.jgonzalez.billar;

import net.iessonferrer.jgonzalez.billar.Bola;

/************************************************************/
/**
 * 
 */
public class Mesa {
	/**
	 * 
	 */
	private Bola[] bolas;
	/**
	 * 
	 */
	private String color;
	/**
	 * 
	 */
	private int anchura;
	/**
	 * 
	 */
	private int altura;

	/**
	 * 
	 */
	public void dibujar() {
	}
};
