// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package net.iessonferrer.jgonzalez.billar;

/************************************************************/
/**
 * 
 */
public enum posicionTipo {
	/**
	 * 
	 */
	ARRIBA_IZQUIERDA,
	/**
	 * 
	 */
	ARRIBA_CENTRO,
	/**
	 * 
	 */
	ARRIBA_DERECHA,
	/**
	 * 
	 */
	ABAJO_IZQUIERDA,
	/**
	 * 
	 */
	ABAJO_CENTRO,
	/**
	 * 
	 */
	ABAJO_DERECHA;
};
