// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package net.iessonferrer.jgonzalez.billar;

import net.iessonferrer.jgonzalez.billar.Bola;

/************************************************************/
/**
 * 
 */
public class Taco {
	/**
	 * 
	 */
	public Bola bola;
	/**
	 * 
	 */
	private int[] longidud;
	/**
	 * 
	 */
	private String color;
	/**
	 * 
	 */
	private float fuerza;
	/**
	 * 
	 */
	private float direccionX;
	/**
	 * 
	 */
	private float direccionY;

	/**
	 * 
	 */
	public void dibujar() {
	}

	/**
	 * 
	 */
	public void golpear() {
	}
};
