// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package net.iessonferrer.jgonzalez.billar;

import net.iessonferrer.jgonzalez.billar.posicionTipo;

/************************************************************/
/**
 * 
 */
public class Tronera {
	/**
	 * 
	 */
	private int radio;
	/**
	 * 
	 */
	private posicionTipo tipoPosicion;

	/**
	 * 
	 */
	public void dibujar() {
	}
};
